# specs/domains/products/paths.yaml

/products:
  get:
    tags:
      - Products
    summary: Retrieve product catalogue
    operationId: getProducts

    parameters:
      - $ref: '../components/parameters/headers.yaml#/CorrelationIdHeader'
      - $ref: '../components/parameters/headers.yaml#/RequestIdHeader'
      - $ref: '../components/parameters/headers.yaml#/TraceParentHeader'
      - $ref: '../components/parameters/headers.yaml#/PageParam'
      - $ref: '../components/parameters/headers.yaml#/PageSizeParam'

    responses:
      '200':
        description: Success
        content:
          application/json:
            schema:
              $ref: '../../components/schemas/product.yaml#/ProductListResponse'
      '400':
        $ref: '../../components/responses/common.yaml#/BadRequest'
      '500':
        $ref: '../../components/responses/common.yaml#/InternalServerError'

  post:
    tags:
      - Products
    summary: Create product
    operationId: createProduct

    parameters:
      - $ref: '../components/parameters/headers.yaml#/IdempotencyKeyHeader'
      - $ref: '../components/parameters/headers.yaml#/CorrelationIdHeader'
      - $ref: '../components/parameters/headers.yaml#/RequestIdHeader'
      - $ref: '../components/parameters/headers.yaml#/TraceParentHeader'
    
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/product.yaml#/Product'

    responses:
      '201':
        description: Created
        content:
          application/json:
            schema:
              $ref: '../../components/schemas/product.yaml#/Product'
      '400':
        $ref: '../../components/responses/common.yaml#/BadRequest'
      '401':
        description: Unauthorized
      '403':
        description: Forbidden
      '500':
        $ref: '../../components/responses/common.yaml#/InternalServerError'

/products/{productId}:
  get:
    tags:
      - Products
    summary: Get product by ID
    operationId: getProductById

    parameters:
      - $ref: '../../shared/headers.yaml#/ProductIdParam'
      - $ref: '../../shared/headers.yaml#/CorrelationIdHeader'

    responses:
      '200':
        description: Success
        content:
          application/json:
            schema:
              $ref: '../../components/schemas/product.yaml#/Product'
      '404':
        $ref: '../../components/responses/common.yaml#/NotFound'
      '400':
        $ref: '../../components/responses/common.yaml#/BadRequest'
      '500':
        $ref: '../../components/responses/common.yaml#/InternalServerError'
