# specs/paths/products.yaml
get:
  tags: [Products]
  summary: Retrieve product catalogue
  operationId: getProducts
  parameters:
    - $ref: '../components/parameters/headers.yaml#/PageParam'
    - $ref: '../components/parameters/headers.yaml#/PageSizeParam'
  responses:
    '200':
      description: Successful response
      content:
        application/json:
          schema:
            $ref: '../components/schemas/product.yaml#/ProductListResponse'
    '400':
      $ref: '../components/responses/common.yaml#/BadRequest'
    '500':
      $ref: '../components/responses/common.yaml#/InternalServerError'

post:
  tags: [Products]
  summary: Create a new product
  operationId: createProduct
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../components/schemas/product.yaml#/Product'
  responses:
    '201':
      description: Product created successfully
      content:
        application/json:
          schema:
            $ref: '../components/schemas/product.yaml#/Product'
    '400':
      $ref: '../components/responses/common.yaml#/BadRequest'
