Product:
  type: object
  required: [id, name, price]
  properties:
    id:
      type: integer
    name:
      type: string
    price:
      type: number
      format: double

ProductListResponse:
  type: object
  properties:
    totalItems:
      type: integer
    page:
      type: integer
    pageSize:
      type: integer
    products:
      type: array
      items:
        $ref: '#/components/schemas/Product'
