openapi: 3.0.3

info:
  title: MyAPITerry Enterprise Platform API
  version: 1.0.0

servers:
  - url: https://api.online-shop.com/v1

security:
  - BearerAuth: []

paths:
  /products:
    $ref: './domains/products/paths.yaml#/products'
  /products/{productId}:
    $ref: './domains/products/paths.yaml#/products~1{productId}'
  /notifications:
    $ref: './domains/notifications/paths.yaml#/notifications'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    CorrelationIdHeader:
      $ref: './shared/headers.yaml#/CorrelationIdHeader'
    PageParam:
      $ref: './shared/headers.yaml#/PageParam'
    PageSizeParam:
      $ref: './shared/headers.yaml#/PageSizeParam'
    ProductIdParam:
      $ref: './shared/headers.yaml#/ProductIdParam'

  responses:
    $ref: './components/responses/common.yaml'

  schemas:
    ErrorResponse:
      $ref: './shared/errors.yaml#/ErrorResponse'
